CREATE DATABASE KT_THU

CREATE TABLE KHANHHANG(
	MAKH VARCHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(50),
	DIACHI NVARCHAR(50),
	DIENTHOAI VARCHAR(15),
	GIOITINH NVARCHAR(10)
);

CREATE TABLE CONGTO(
	MACT VARCHAR(10) PRIMARY KEY,
	MAKH VARCHAR(10),
	TENCT NVARCHAR(50),
	SODIENSD FLOAT,
	MUCGIA FLOAT,
	CONSTRAINT FK1 FOREIGN KEY (MAKH) REFERENCES KHANHHANG(MAKH)
);

--B2
IF OBJECT_ID('B2') IS NOT NULL 
DROP PROC B2
GO
CREATE PROC B2(
	@MACT VARCHAR(10),
	@MAKH VARCHAR(10),
	@TENCT NVARCHAR(50),
	@SODIENSD FLOAT,
	@MUCGIA FLOAT
)
AS
	IF @MAKH IS NULL OR @MACT IS NULL OR @TENCT IS NULL OR @SODIENSD IS NULL OR @MUCGIA IS NULL
	PRINT 'Không được để trống'
	ELSE 
	INSERT INTO CONGTO VALUES (@MACT,@MAKH,@TENCT,@SODIENSD,@MUCGIA)
--
EXEC B2 'CT01','KH02',N'CT THANH',40,5000
EXEC B2 'CT02','KH02',N'CT THANH',67,9000
EXEC B2 'CT03','KH01',N'CT THANH',50,7000
SELECT * FROM CONGTO
--------------------B2B
IF OBJECT_ID('B2B') IS NOT NULL 
DROP PROC B2B
GO
CREATE PROC B2B(
	@MAKH VARCHAR(10),
	@TENKH NVARCHAR(50),
	@DIACHI NVARCHAR(50),
	@DIENTHOAI VARCHAR(15),
	@GIOITINH NVARCHAR(10)
)
AS
	IF @MAKH IS NULL OR @TENKH IS NULL OR @DIACHI IS NULL OR @DIENTHOAI IS NULL OR @GIOITINH IS NULL
	PRINT 'Không được để trống'
	ELSE 
	INSERT INTO KHANHHANG VALUES (@MAKH,@TENKH,@DIACHI,@DIENTHOAI,@GIOITINH)
EXEC B2B 'KH01',N'THANH',N'NGHE AN','09874243',N'NAM'
EXEC B2B 'KH02',N'THANH 2',N'HA NOI','09874253',N'NAM'
EXEC B2B 'KH03',N'THANH 3',N'VINH','09874247',N'NU'
SELECT * FROM KHANHHANG
--B3
IF OBJECT_ID('B3') IS NOT NULL
DROP FUNCTION B3
GO
CREATE FUNCTION B3 (@MAKH VARCHAR(10))
RETURNS INT
AS
BEGIN
	RETURN (SELECT SUM(SODIENSD) FROM CONGTO WHERE MAKH = @MAKH GROUP BY MAKH)
END
--
SELECT DBO.B3('KH02') AS TONG_SO_DIEN_TT
--C4 XOA
IF OBJECT_ID ('B4') IS NOT NULL
DROP PROC B4
GO
CREATE PROC B4(@MAKH VARCHAR(10))
AS
BEGIN TRY
	--BANG TAM
	--DECLARE @TAM TABLE (MA VARCHAR(10))
	--INSERT INTO @TAM
	--SELECT FROM
	BEGIN TRAN
		--KHOA NGOAI
		DELETE CONGTO
		WHERE MAKH=@MAKH
		--KHOA CHINH
		DELETE KHANHHANG
		WHERE MAKH=@MAKH
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
--
EXEC B4 'KH01'
--B5 VIEW 
IF OBJECT_ID('B5') IS NOT NULL
DROP VIEW B5
GO
CREATE VIEW B5
AS
	SELECT C.MAKH,TENKH,DIACHI,MACT,SODIENSD,MUCGIA,(MUCGIA*SODIENSD) AS THANHTIEN,IIF(SODIENSD > 300,N'NHIỀU',N'VỪA ĐỦ') AS TRẠNG_THAI
	FROM CONGTO C JOIN KHANHHANG K ON K.MAKH = C.MAKH

SELECT * FROM B5