CREATE DATABASE LAB1LMS
GO
USE LAB1LMS
GO

CREATE TABLE PHONGBAN
(
TENPHG NVARCHAR(10),
MAPHG NVARCHAR(10),
TRPHG NVARCHAR(20),
NG_NHANCHUC NVARCHAR(20),
CONSTRAINT KC PRIMARY KEY(MAPHG)
)
GO
CREATE TABLE NHANVIEN
(
HONV NVARCHAR(50),
TENLOT NVARCHAR(50),
TENNV NVARCHAR(50),
MANV NVARCHAR(10),
NGAYSINH DATE,
DIACHI NVARCHAR(MAX),
PHAI NVARCHAR(100),
LUONG FLOAT,
MA_NQL NVARCHAR(10),
PHG NVARCHAR(10),
CONSTRAINT KC_NV PRIMARY KEY(MANV),
MAPHG NVARCHAR(10),
CONSTRAINT FK_5 FOREIGN KEY(MAPHG) REFERENCES PHONGBAN(MAPHG),
)
SELECT * FROM NHANVIEN
WHERE MAPHG = '4';

SELECT * FROM NHANVIEN
WHERE LUONG = '30000';

SELECT * FROM NHANVIEN
WHERE LUONG >=25000 AND MAPHG = '4' OR LUONG >=30000 AND MAPHG = '5';

SELECT CONCAT(HONV,TENLOT,TENNV) as họten
FROM NHANVIEN
WHERE DIACHI = N'TP HCM';
SELECT CONCAT(HONV,TENLOT,TENNV) as họten
FROM NHANVIEN
WHERE HONV LIKE N'C%';

SELECT NGAYSINH,DIACHI, CONCAT(HONV,TENLOT,TENNV) as họten
FROM NHANVIEN
WHERE CONCAT(HONV,TENLOT,TENNV) = N'Dinh Ba Tien'